### PR TITLE
demonstrate runtime error for @nebular/theme

### PR DESCRIPTION
**Pull request by rayman1104**
Repro for https://github.com/angular/ngcc-validation/issues/529

### CODE REVIEW

**Comment by rayman1104** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
The error is that the injector is not able to create `NbScrollStrategyOptions`. This is because it is not finding the injectable definition for this type.

I can see that ngcc is doing the right thing:

```ts
    NbScrollStrategyOptions.ngInjectableDef = ɵɵdefineInjectable({ factory: function NbScrollStrategyOptions_Factory() { return new NbScrollStrategyOptions(ɵɵinject(NbLayoutScrollService), ɵɵinject(ScrollDispatcher$1), ɵɵinject(NbViewportRulerAdapter), ɵɵinject(NgZone), ɵɵinject(NB_DOCUMENT)); }, token: NbScrollStrategyOptions, providedIn: "root" });
```

The problem is that `getInjectableDef()` is not doing the right thing... See https://github.com/angular/angular/blob/86104b82b8af87efab46db50962e6b16f3724672/packages/core/src/di/interface/defs.ts#L192-L202

The code is effectively:

```ts
export function getInjectableDef<T>(type: any): ɵɵInjectableDef<T>|null {
  const def = (type.ɵprov || type.ngInjectableDef) as ɵɵInjectableDef<T>;
  return def && def.token === type ? def : null;
}
```

Checking the `def.token === type` is to prevent bringing in the definition from the `type`'s super class.

But in this case it is wrong because, while `ɵprov` is inherited and so should not be used `ngInjectableDef` is available and not inherited. So that one should be used.

**Comment by petebacondarwin** [comment]
Actually I just realised that ngcc should be using the "new" name (i.e. `ɵprov` replaced `ngInjectableDef`). So perhaps there are two fixes...

1) make core more resilient to a derived class using the old name when a super class uses the new name
2) fix ngcc to output the new name rather than the old name

**Comment by petebacondarwin** [comment]
Actually!!

It turns out that this `ngInjectableDef` was already in the library published to npm, so ngcc had no hand in defining it. I checked and ngcc will always add the correct `ɵprov` property. So it is only legacy libraries that have this problem.

Therefore the fix really is only 1) from above.

**Pull request merged**
