### PR TITLE
chore: add ngcc config file in order to enable NativeScript package to be compiled by ngcc

### PR DESCRIPTION
**Pull request by VladimirAmiorkov**
I am not sure if this is valid for this validation repo but in order for NativeScript to be considered by ngcc for compilation it requires a custom `ngcc.config.js` file that tells ngcc the `entryPoints` and to `ignoreMissingDependencies`.

Other wise the `nativescript-angular` package is simply ignored by ngcc, it does not throw and error and the web app will run faking that `nativescript-angular` package is compatible while it is not as it requires `ngcc` to run over it.

if this is not the way to make sure that ngcc run over `nativescript-angular` package in this validation repo please let me know and I will update my PR.

### CODE REVIEW

**Comment by VladimirAmiorkov** [comment]
@googlebot I signed it!

**Comment by mgechev** [comment]
@VladimirAmiorkov is that the recommended way to use `nativescript-angular` with version 9? If the answer is yes, we can merge the PR. Alternatively, if you're planning to provide this configuration in an alternative way, we can hold this off for a bit.

**Comment by VladimirAmiorkov** [comment]
Hi @mgechev ,

Thanks for the lightning fast response. We do plan to ship an `ngcc.config.js` file with the `@nativescript-angular` package that comes when you add `nativescript-angular` but when 9.0.0 is released. We have not considered shipping it in the package before that as it is not required for anything for the package to work. But I could discuss this with the team and see if we should ship it now in order for you guys to be able to validate the NativeScript package sooner.

For now if you think that this PR is ok I am fine with merging it now and if we decided to ship the ngcc config before 9.0.0 I can revert this change. Also having this config and an config inside `@nativescript-angular` package should not be a problem and it should work the same.

**Comment by mgechev** [comment]
Sounds good! Looking at CircleCI looks like `nativescript-angular` is still failing because of a dependency on the `Renderer`.

Are you planning to migrate this as part of the next release?

**Comment by VladimirAmiorkov** [comment]
Yes I am currently working on resolving all 9.0.0 braking changes and will probably prepare an RC that we could swap in tour testing. I will keep you posted.

**Comment by VladimirAmiorkov** [comment]
Hi @mgechev ,

I changed this PR to simply use the new version of the `nativescript-angular` package that contains our fixes required for 9.0.0.

Note that the even with this version of the `nativescript-angular` package the Ivy (ngcc compile) validation will again fail due to this ongoing issue: https://github.com/angular/angular/issues/33734 , but at least now the validation will be correct :)

**Comment by mgechev** [comment]
Looks like the build is failing. Would you update `yarn.lock` as well?

**Comment by VladimirAmiorkov** [comment]
Yeah sorry was not aware that this used yarn. Should be ok now.

**Comment by VladimirAmiorkov** [comment]
Hi @mgechev ,

I see that there is a bot that is constantly updating the dep of `nativescript-angular` to the latest version and merging it into the master which is not the one that I have made with the Ivy preparations. this is causing my PR to requires constant conflict resolution :) , how can we overcome this bot and tell him to not automatically update the `nativescript-angular` version ?

**Comment by mgechev** [comment]
You can update the [renovate config](https://github.com/angular/ngcc-validation/blob/master/renovate.json) in [ignoreDeps](https://docs.renovatebot.com/configuration-options/#ignoredeps).

**Comment by VladimirAmiorkov** [comment]
Nice, got it.

**Pull request merged**
