### PR TITLE
Add and update Kendo UI packages

### PR DESCRIPTION
**Pull request by tsvetomir**
* Add projects for most of the Kendo UI packages. Most of them work great with Ivy 🎉
* Demonstrates an issues with the Grid component where `ngcc` produces invalid exports for classes with duplicate names:

```ts
ERROR in ../../node_modules/@progress/kendo-angular-grid/dist/es2015/index.d.ts:101:9 - error TS2304: Cannot find name 'PDFMarginComponent'.                                                                                         

101 export {PDFMarginComponent as PDFMarginComponent$1};
            ~~~~~~~~~~~~~~~~~~
../../node_modules/@progress/kendo-angular-grid/dist/es2015/index.d.ts:102:9 - error TS2304: Cannot find name 'PDFTemplateDirective'.                                                                                                

102 export {PDFTemplateDirective as PDFTemplateDirective$1};
            ~~~~~~~~~~~~~~~~~~~~
```

In this case `PDFMarginComponent` and `PDFTemplateDirective` are declared in both `@progress/kendo-angular-pdf-export` and `@progress/kendo-angular-grid`. They end up in different modules and have different selectors though.

@mgechev help 😅

### CODE REVIEW

**Comment by mgechev** [comment]
@tsvetomir would you add the projects to `infra/failing-projects.json` so we can merge the PR. I'll add the failure to our tracker.

**Comment by mgechev** [comment]
There are a few more failures. Would you incorporate them in the `failing-projects.json` as well?

**Comment by tsvetomir** [comment]
No actual issues in the rest of the failing projects— just some failing e2e tests.

**Comment by tsvetomir** [comment]
Should be good to go 🚀

**Comment by mgechev** [comment]
Thanks for the fix! Just resolved a merge conflict. Will wait to see if the build is still passing and merge.

**Comment by tsvetomir** [comment]
I see we've slipped in a test for the Date constructor... yep, it works 😅

**Comment by petebacondarwin** [comment]
I think this PR should solve the problems with this package: https://github.com/angular/angular/pull/34254

**Pull request merged**
