### PR TITLE
add ngx-wig project

### PR DESCRIPTION
**Pull request by stevermeister**

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx, @stevermeister! Don't forget to add the dependency in the `package.json` and `yarn.lock` as well.

**Comment by stevermeister** [comment]
@gkalpak thank you! I thought `npm run add-project` was doing it for me, sorry.
added

**Comment by stevermeister** [comment]
and now for some reason, I see the problem with `angular-calendar` that is not related for my project

**Comment by gkalpak** [comment]
@stevermeister, it seems you updated a whole lot of unrelated dependencies in `yarn.lock` :grin:
Please make sure only the changes related to adding `ngx-wig` (and its dependencies) are retained in `yarn.lock`.

**Comment by gkalpak** [comment]
It seems there are more conflicts 😞
@stevermeister, can you resolve the conflicts, squash the commits into one and ping me (so we can get this merged before more conflicts arise :smiley:)?

**Comment by stevermeister** [comment]
@gkalpak looks like I made it :)

**Pull request merged**
