### PR TITLE
ci: configure all projects which are not listed in `ng-build-projects.json` to use `ng e2e`

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Comment by mgechev** [comment]
I merged the PR that updates the protractor configs first. Would you rebase?

**Comment by alan-agius4** [comment]
Will do it tmr, as I am AFK.

Can you also check the convo in the NGCC channel please? Thanks.

**Comment by mgechev** [comment]
@alan-agius4 can we address the comment about platform server and other similar packages? Otherwise, I think we're good to go.

**Comment by alan-agius4** [comment]
@mgechev, will be doing that tmr 🙂, sorry for the delay.

**Comment by mgechev** [comment]
No worries!

**Comment by alan-agius4** [comment]
@mgechev, this should be good to go!

**Pull request merged**
